///<reference path='../../../../../../../test/lib/YUITest.d.ts'/>

///<reference path='../../../../../../../src/org/puremvc/typescript/interfaces/ICommand.ts'/>
///<reference path='../../../../../../../src/org/puremvc/typescript/interfaces/INotification.ts'/>

///<reference path='../../../../../../../src/org/puremvc/typescript/patterns/observer/Notification.ts'/>

///<reference path='SimpleCommandTestCommand.ts'/>
///<reference path='SimpleCommandTestVO.ts'/>
///<reference path='SimpleCommandTestSub.ts'/>

module puremvc
{
	"use strict";

	import YUITest = module("YUITest");

	/**
	 * Test the PureMVC SimpleCommand class.
	 */
	export class SimpleCommandTest
	{
		/**
		 * The name of the test case - if not provided, one is automatically generated by the
		 * YUITest framework.
		 */
		name:string = "PureMVC SimpleCommand class Tests";

		/**
		 * Tests if constructing the <code>SimpleCommand</code> also call its super by testing for
		 * the existence of its <code>Notifier</code> superclass facade instance.
		 */
		testConstructor():void
		{
			// Create a new subclass of Notifier and verify that its facade has well been created
			var simpleCommandTestSub:SimpleCommandTestSub = new SimpleCommandTestSub();

			// test assertions
			YUITest.Assert.isTrue
			(
				simpleCommandTestSub.hasFacade(),
				"Expecting simpleCommandTestSub.hasFacade() === true"
			);
		}

		/**
		 * Tests the <code>execute</code> method of a <code>SimpleCommand</code>.
		 *
		 * This test creates a new <code>Notification</code>, adding a
		 * <code>SimpleCommandTestVO</code> as the body. It then creates a
		 * <code>SimpleCommandTestCommand</code> and invokes its <code>execute</code> method,
		 * passing in the note.
		 *
		 * Success is determined by evaluating a property on the object that was passed on the
		 * <code>Notification</code> body, which will be modified by the SimpleCommand.
		 */
		testSimpleCommandExecute():void
		{
			// Create the VO
			var vo:SimpleCommandTestVO = new SimpleCommandTestVO(5);

			// Create the Notification (note)
			var note:INotification = new Notification( 'SimpleCommandTestNote', vo );

			// Create the SimpleCommand
			var command:ICommand = new SimpleCommandTestCommand();

			// Execute the SimpleCommand
			command.execute(note);

			// test assertions
			YUITest.Assert.areEqual
			(
				10,
				vo.result,
				"Expecting vo.result == 10"
			);
		}
	}
}